sudo: required
language: javascript
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev
install:
- npm install
- docker pull ubuntu:latest
script:
- npm test
